title: Ricardo Lopes's Website
author: Ricardo Lopes
email: ricardoapl.dev@gmail.com
description: >-
  I blog about cybersecurity, programming, and other tech-related topics.

baseurl: ""
url: "https://ricardoapl.github.io"

github_username: "ricardoapl"
hackthebox_profile: "1522115"
hackthebox_username: "ricardoapl"
linkedin_username: "ricardoapl"

theme: minima

plugins:
  - jekyll-feed

header_pages:
  - about.markdown
